Домашнее задание: функции с случайными числами
htmlacademy-javascript/205191-keksobooking-24 pull request #2
Opened 2021-09-25 14:55 UTC by vsim1964

Плюс временный файл algoritm.md, там намечаю, что делать

2021-09-26 11:08 UTC, KHarpushkina requested changes
Отличная работа! Я оставила несколько комментариев, чтобы улучшить твой код. А также проверь ошибки, которые показывает eslint.

2021-09-26 11:08 UTC, KHarpushkina commented on js/main.js
> +/*
Потренируйся ещё в написании функций. Вот примеры функций, которые ты можешь реализовать
1) Функция, возвращающая сумму простых чисел из переданного диапазона включительно. 
2) Функция, которая принимает целое число в качестве аргумента и возвращает «Even» для четных чисел или «Odd» для нечетных чисел.
3) Функция, которая принимает 2 целых числа и строку, описывающую одно из математических действий: сложение, вычитание, умножение и деление ('add', 'subtraction', 'multiply', 'divide'). В зависимости от переданного действия, должен быть возвращен соответствующий результат.

2021-09-27 10:28 UTC, vsim1964 commented on js/main.js
> +    console.log('Значения введенных чисел должны быть бльше или равны 0');
Согласен, лучше вернуть. Но пока я не могу точно сказать, куда именно возвращать, как временный вариант предлагаю оставить вывод в консоль

2021-09-27 10:28 UTC, vsim1964 commented on js/main.js
> +    console.log('Значение числа max  должно быть больше значение числа min');
Согласен, лучше вернуть. Но пока я не могу точно сказать, куда именно возвращать, как временный вариант предлагаю оставить вывод в консоль

2021-09-27 10:28 UTC, vsim1964 commented on js/main.js
> +function randomInteger(min, max) {
Сдеалано

2021-09-27 10:28 UTC, vsim1964 commented on js/main.js
> +function randomFloat(min, max, n) {
сделано

2021-09-27 10:29 UTC, vsim1964 commented on js/main.js
> +    console.log('Значение числа max  должно быть больше значение числа min');
Согласен, лучше вернуть. Но пока я не могу точно сказать, куда именно возвращать, как временный вариант предлагаю оставить вывод в консоль

2021-09-27 10:34 UTC, vsim1964 commented on js/main.js
> +console.log(randomInteger(50, 52));
Сделано

2021-09-27 10:37 UTC, vsim1964 commented on js/main.js
> +  return +num.toFixed(n);
метод toFixed преобразует число в строку, поэтому пришлось сделать обратную операцию

2021-09-27 10:37 UTC, vsim1964 commented on js/main.js
> +/*
Тренируюсь. Спасибо за замечания и советы!

2021-09-27 10:40 UTC, vsim1964 commented on algoritm.md
> +### ИНИЦИАЛИЗАЦИЯ
Это временный файл, имеющий чисто подсобное значение для меня, потом удалю

2021-09-27 10:42 UTC, vsim1964 commented on js/main.js
> +  let num = (Math.random() * (max - min)) + min;
const в моем понимании не меняет значения, а само понятие случайного числа подразумевает изменение значения, следовательно, постоянная здесь не годится. Так я рассуждаю? В чем я не прав?

2021-09-27 13:14 UTC, KHarpushkina approved these changes

2021-09-27 13:14 UTC, merged