Первая попытка генерации объектов
htmlacademy-javascript/205191-keksobooking-24 pull request #3
Opened 2021-10-03 21:51 UTC by vsim1964

Здравствуйте!
У меня возникло затруднение  с пунктом :
**features, массив строк — массив случайной длины из значений: wifi, dishwasher, parking, washer, elevator, conditioner. Значения не должны повторяться.**
При генерации массив уменьшается с каждой итерацией и получается , что он исчезает.
Я присоединил два файла test. js, test2.js.
Там я отрабатывал метод. Причем в  test. js все вроде работает
Пока не могу придумать, что сделать

2021-10-05 13:18 UTC, KHarpushkina requested changes

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +const avatars = [
Названия констант (постоянных значений) должны быть написаны заглавными буквами

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +const avatars = [
То же самое относится к значениям ниже

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +  const lngsRandomInteger = getRandomFloat(139.70000, 139.80000, 5);
В коде лучше не использовать «магические значения». К примеру значения 35.65000 и 35.70000.  Под каждое из них лучше завести отдельную константу

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +      address: {
Значение address должно быть строкой, которая составляется из географических координат по маске {{location.lat}}, {{location.lng}}.

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +  const propertiesEnd = getRandomInteger(propertiesStart + 1, 7);
Отличное решение!

2021-10-05 13:18 UTC, KHarpushkina commented on js/main.js
> +      avatar: avatars[avatarsRandomIndex],
По заданию адреса изображений не должны повторяться. В вашей реализации есть шанс, что рандом выдаст один и тот же индекс несколько раз.

2021-10-05 13:18 UTC, KHarpushkina commented on index.html
> +  <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js"></script>
Не вижу, чтобы где-то использовался lodash. Если он не используется, то незачем его импортировать

2021-10-05 16:40 UTC, vsim1964 commented on js/main.js
> +const avatars = [
Сделано

2021-10-05 16:45 UTC, vsim1964 commented on js/main.js
> +  const lngsRandomInteger = getRandomFloat(139.70000, 139.80000, 5);
СДЕЛАНО

2021-10-05 16:46 UTC, vsim1964 commented on index.html
> +  <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js"></script>
Я пытался его использовать, забяыл удалить строчку. Удалил

2021-10-05 16:58 UTC, vsim1964 commented on js/main.js
> +      address: {
Реализовано с помощью шаблонных выражений

2021-10-05 18:26 UTC, vsim1964 commented on js/main.js
> +      avatar: avatars[avatarsRandomIndex],
Переделал. Вместо случайного числа поставил в индекс значение i из цикла, а чтобы область видимости совпала переделал let на var.  Вроде бы критериями не запрещается

2021-10-05 18:26 UTC, vsim1964 commented on js/main.js
> +      avatar: avatars[avatarsRandomIndex],
Если это будет вредным впоследствии, значит, что-то другое надо будет придумать

2021-10-05 19:05 UTC, vsim1964 commented on js/main.js
> +      avatar: avatars[avatarsRandomIndex],
Привязал индекс массива аватарок  к переменной  i, вынеся ее создание в нужную область видимости

2021-10-06 10:26 UTC, KHarpushkina requested changes

2021-10-06 10:26 UTC, KHarpushkina commented on js/main.js
> +console.log(ADVERTS);
Убери ненужный console.log

2021-10-06 10:26 UTC, KHarpushkina commented on js/main.js
> +  const LNGS_RANDOM_INTEGER = getRandomFloat(FROM_LONGITUDE, TO_LONGITUDE, 5);
Все ещё остались "магические значения" 
Все числа, которые взяты непонятно откуда (читая код, непонятно, что они означают), лучше определять в отдельной переменной. 

Числа, которые отвечают за границу индекса массива, можно получить динамически, используя метод массива length. Тогда, если массив измениться не придётся вручную менять это значение.

Остальные значения лучше вынести в отдельные переменные.

2021-10-06 16:15 UTC, merged